#!/bin/bash
set +e

echo '-------------------'
echo 'docker-compose stop'
docker-compose stop

echo '--------------------'
echo 'sudo rm -rf tmp/pids'
sudo rm -rf tmp/pids

echo '########################'
echo 'BEGIN: docker-compose up'
echo '########################'
echo 'View this app in your web browser at'
echo 'http://localhost:3000/'
docker-compose up
