name: Staging deploy
on:
  push:
    branches:
      - ssl-and-dns
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: ssh to staging server, stop services, get fresh checkout, restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STG_SERVER_WEST }}
          key: ${{ secrets.STG_PRIVATE_KEY_WEST }}
          username: ec2-user
          script: |
            cd banana-rails || exit 1
            sudo docker-compose down
            cd ..
            sudo rm -rf banana-rails
            git clone -b ssl-and-dns git@github.com:FoodIsLifeBGP/banana-rails.git --depth=1
            cd banana-rails || exit 1
            sudo docker-compose up -d