name: Staging deploy
on: 
  push:
    branches: 
      - prealpha/main
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code so we can access deploy.sh
        uses: actions/checkout@v2
      - name: show contents of checkout
        run: |
          ls -al ${{ github.workspace }}
          echo ${{ github.workspace }}
          cat ${{ github.workspace }}/deploy.sh
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STG_SERVER }}
          key: ${{ secrets.STG_PRIVATE_KEY }}
          username: ubuntu
          script: |
            cd banana-rails
            sudo docker-compose up -d
