name: Staging deploy
on: 
  push:
    branches: 
      - prealpha/main
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ssh -i ${{ secrets.STG_PRIVATE_KEY }} ubuntu@${{ secrets.STG_SERVER }} 'ls -al; sudo docker ps'
