name: Tests
on: push

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        id: checkout
      - name: Docker compose
        run: docker-compose up
      - name: Run via docker
        run: docker-compose run --rm console bash -c "bundle install && rails db:prepare && rspec"
